2024-11-30 19:16:36,049| (WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Daniil\Documents\PROGS\pichon\HomeWorks\myDirectory\module12tests\module12_4.py", line 74, in test_run
    runner1 = Runner(5)
              ^^^^^^^^^
  File "C:\Users\Daniil\Documents\PROGS\pichon\HomeWorks\myDirectory\module12tests\module12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-30 19:16:36,050| (WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Daniil\Documents\PROGS\pichon\HomeWorks\myDirectory\module12tests\module12_4.py", line 63, in test_walk
    runner = Runner('TestWalk', -10)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniil\Documents\PROGS\pichon\HomeWorks\myDirectory\module12tests\module12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -10
